CREATE TABLE `ai_coin_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `refreshTime` bigint(20) DEFAULT '1' COMMENT '刷新时间',
  `status` int(3) DEFAULT '0' COMMENT '是否启用刷新币对',
  `flag` int(3) DEFAULT '0' COMMENT '是否正在运行',
  `description` varchar(200) NOT NULL COMMENT '参考币对描述',
  `refPayCoin` varchar(20) NOT NULL COMMENT '参考币-交易币种-基础币：如USDT',
  `symbol` varchar(50) NOT NULL COMMENT 'dxfeed参考币对',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `country` varchar(50) DEFAULT NULL COMMENT '来源',
  `opol` varchar(50) DEFAULT NULL COMMENT 'dxfeed参考币对',
  `baseCurrency` varchar(50) DEFAULT NULL COMMENT '项目币',
  `multiplier` varchar(50) DEFAULT NULL COMMENT '倍率',
  `tradingHours` varchar(80) DEFAULT NULL COMMENT '交易时间',
  `bitfinexSymbol` varchar(50) DEFAULT NULL,
  `bitflyerSymbol` varchar(50) DEFAULT NULL,
  `cxbitsSymbol` varchar(50) DEFAULT NULL,
  `cxbmexSymbol` varchar(50) DEFAULT NULL,
  `cxmateSymbol` varchar(50) DEFAULT NULL,
  `cxokftSymbol` varchar(50) DEFAULT NULL,
  `cxplnxSymbol` varchar(50) DEFAULT NULL,
  `ethfinexSymbol` varchar(50) DEFAULT NULL,
  `gdaxSymbol` varchar(50) DEFAULT NULL,
  `krakenSymbol` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
